spring.application.name=healthtracking
spring.cloud.gcp.firestore.project-id="healthtracking-c0d9c"
spring.cloud.gcp.firestore.credentials.location=classpath:healthtracking-c0d9c-firebase-adminsdk-l3qwb-2b4379766b.json










